### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by goferito** [zaid/vim-rec#1]
Hi!

Thanks a lot for publishing this!

I just wanted to suggest if possible to have some extra functionality to format multiline text by starting lines with "+". 

I've added this to my vimrc, but maybe it can be integrated in this plugin:
`autocmd BufRead,BufNewFile *.rec vmap <Leader>t :s/^/+ /<cr>:noh<cr>`

This way i can select some text and append the + easily. But maybe it could be a nicer solution to add the + on a new line, and the if empty on a second new line remove it? That way we can make vim more friendly to write rec files.

I'm open to discuss the idea, or try something myself. I just don't have a clue how to start, that's why I make the suggestion firts :smile:

**Comment by zaid** [comment]
Hi @goferito 

> Thanks a lot for publishing this!

You're welcome! I'm glad that you're finding it useful 😃

> I just wanted to suggest if possible to have some extra functionality to format multiline text by starting lines with "+".

To be honest, I want to use GNU Recutils a bit more and see what pain points I encounter before I start adding keyboard maps for formatting text.

In this case though, the alternative which i'm using is visual block insertion (`help :blockwise-operators`) which is a few more clicks than your `autocmd` map.

I think that it is perfectly fine to have that `autocmd` in your `.vimrc` though especially if it makes your life easier when it comes to inserting those multiline markers 👍 

Thank you for the suggestion and let me know if there is anything else that you'd like me to add. I'm hoping to add some basic folding support soon.

**Comment by zaid** [comment]
I added this to the list of `TODO` items so I'm going to mark this issue as closed for now and revisit this when I'm adding keymaps.
