### ISSUE TITLE
Project license, new release

### ISSUE THREAD

**Issue by ml-** [zaid/vim-rec#4]
I just created a [package on the Arch User Repository](https://aur.archlinux.org/packages/vim-rec/) for vim-rec and during the packaging I noticed that this project lacks a license and hasn't seen a new release since february.

Could you add a license to the project or is there a reason there is none?
Would also appreciate a new tag/release as I'd like to provide the most recent changes to AUR users. There were a lot of interesting changes sind 0.0.3.

Thanks.

**Comment by zaid** [comment]
@ml- Thank you for creating the Arch package! I'll tag a new release tonight and add the missing license.

**Comment by zaid** [comment]
@ml- I added the missing `LICENSE` file and published a new `0.0.4` release.
